### ISSUE TITLE
AFC-1150 Jobseeker-view

### ISSUE THREAD

**Issue by Radhika435** [vertelab/odoo-af#467] opened 2020-12-08 16:19 UTC
**Userstory:** 
As a user, I want to add/ change the education level field in the 
partner_education_views
(outplacement_res.partner)

Step 1: Change the name of the existing *education level* field to Highest education level and place it above the *Sun-code* field as shown in the picture below. 
![image](https://user-images.githubusercontent.com/59916603/101524838-bdf2ad00-398a-11eb-8b07-bf4d17365121.png)

Field specification:

| Field name         | Label                               |    Field type                                                      |   Relation
| ------------------| ---------------------------|---------------------------------------------------|-------------------------------
| education_level  | Highest education level  | Many to one and description (default name)  | res.partner.education_level

 
Step 2: A user must be able to create,delete and edit  all the records corresponding to the modules.
![image](https://user-images.githubusercontent.com/59916603/101604228-ec12d400-3a00-11eb-9fb2-8f4345e73075.png)
 
Step 3: Need to add the existing fields (hidden) from CRM. Following fields needs to be added 
![image](https://user-images.githubusercontent.com/59916603/101604828-c0441e00-3a01-11eb-96e0-42b1fde1d459.png)

| Field name                | Label                               |    Field type                                 |   Relation
| -----------------------| ---------------------------|------------------------------------|-------------------------------
|sun_ids                       | SUN code                       |  many to many_tags to res.sun   | res.sun
| -----------------------| ---------------------------|------------------------------------|
| foriegn_education     |  Foriegn education         | boolean                                                            |
| -------------------------------- | --------------------------------|-------------------------------------|-------------------------------
| foriegn_education_approved  | Foriegn education approved  |boolean                                         
| ------------------------| ---------------------------|---------------------------------------------------|-------------------------------
| driving_license_class  | Driving license class        | one to many                                                     | res.drivers_license
| ------------------------| ---------------------------|---------------------------------------------------|-------------------------------
| has_car                       | Has access to car            | boolean                                                             | 

**Module name:** (added by Nils or Fredrik)
odoo-outplacement/outplacement_partner_education
**Development Branch name:** 
Dev-12.0-[CRM/DAFA]-Sprint-[number]-AFC-1150

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by FredrikArvas** [comment] 2020-12-13 21:07
This issue is a duplicate of AFC-1152 . I close this now.
![image](https://user-images.githubusercontent.com/9428370/102024004-866f7080-3d8f-11eb-84b2-480b7c0fa2fc.png)

**Closed as completed by FredrikArvas** 2020-12-13 21:07 UTC
Labels: enhancement
