### ISSUE TITLE
[IMP] AFC-1550 - improvements web_dashboard_fenix

### ISSUE THREAD

**Issue by Radhika435** [vertelab/odoo-af#476] opened 2020-12-14 12:25 UTC
**Userstory:** 
As a user, I want to add some changes on the dashboard

• Only user first name should appear in the dashboard.
•  All the dashboard menus must be on the horizontal menu.
•  Need clear description of menu text for easy understanding of the users
•  Change required  so that you can assign a "note" to one: "user", "group", "all"
• Need to add the relevant icons on the list (if possible)
• Change  the Image size so that the images sizes must be same for all users.
• Show difference between boxes (boxes) with color.

**Module name:** (added by Nils or Fredrik)
web_dashboard_fenix

**Development Branch name:** 
Dev-12.0-[CRM/DAFA]-Sprint-[number]-AFC-1550-...

**Target Branch name:** 
https://github.com/vertelab/odoo-xxx/tree/...

**Module type:** 
Application/Property/Resource/Glue/API module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Description to the manifest:** 
This module/update...

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 28 hours  (With discussion and Development)

**Comment by rupareliyahemangi145** [comment] 2020-12-14 14:24
Hello @Radhika435 

Some points are remaining on this issue. So I will create PR tomorrow.

**Comment by FredrikArvas** [comment] 2020-12-14 15:22
Hi, 
please make a name-change also to web_dashboard_dafa, and make the old module with installable = false 
It needs to be two modules, until we have uninstalled in all servers.

**Comment by rupareliyahemangi145** [comment] 2020-12-15 04:55
Ok @FredrikArvas

**Comment by rupareliyahemangi145** [comment] 2020-12-15 06:28
Hello @FredrikArvas  and @Radhika435 

I have create PR https://github.com/vertelab/odoo-web/pull/19 for this issue.

Here video links for changes: 
https://www.loom.com/share/7f57f18095014610bfaedc15f42cb632
https://www.loom.com/share/8b6373d78c294128b4cb03eedd6afd8b

Remaining points are:
 • Change required so that you can assign a "note" to one: "user", "group", "all"
- Radhika asked to skip for now


 • Change the Image size so that the images sizes must be same for all users.
- I tried but its not possible because it is based on select image class.

Please check it and let me know if anything. 

@FredrikArvas Old module is already installable False
 https://github.com/vertelab/odoo-af/blob/Dev-12.0-Fenix-Sprint-02/fenix_dashboard/__manifest__.py

Thanks

Regards,
Hemangi

**Comment by FredrikArvas** [comment] 2020-12-15 06:48
@rupareliyahemangi145 
Please move the "My Dashboard Config"-menu from the left menu to top area.
![image](https://user-images.githubusercontent.com/9428370/102180921-f40fbf80-3ea9-11eb-96ca-408b92af93bb.png)

**Comment by rupareliyahemangi145** [comment] 2020-12-15 06:50
Ok @FredrikArvas Let me do it.

**Comment by rupareliyahemangi145** [comment] 2020-12-15 06:53
![dashboard_menu](https://user-images.githubusercontent.com/36560391/102181273-44017d00-3ed0-11eb-9b8d-94b3252808cb.png)
 Is this ok? @FredrikArvas

**Comment by FredrikArvas** [comment] 2020-12-15 08:01
@rupareliyahemangi145  Brilliant!

**Comment by rupareliyahemangi145** [comment] 2020-12-15 08:07
Thanks @FredrikArvas Pushed code in same PR for this change.

**Comment by arturchilangwa-vertel** [comment] 2020-12-15 09:43
is now merged https://github.com/vertelab/odoo-web/pull/19

**Comment by Radhika435** [comment] 2021-01-14 10:38
Hi @rupareliyahemangi145 
Hope you are doing great!
I need some small fixes in the dashboard development.
Step 1: I need  to import the welcome text etc to configure the dashboard to multiple users with the help of csv file check if this possible?
Step 2: Delete the selection of users  on the "Update my Dashboard configuration" see the picture below
![image](https://user-images.githubusercontent.com/59916603/104579780-b777e500-565c-11eb-9e12-c235c03db283.png)
As the selection must be based on user groups.

FYI @FredrikArvas 

BR,
Radhika Thadivaka

**Comment by rupareliyahemangi145** [comment] 2021-01-15 07:47
Ok @Radhika435 I will check it.

**Comment by rupareliyahemangi145** [comment] 2021-01-15 10:53
Hello @Radhika435  and @FredrikArvas 

I have create PR https://github.com/vertelab/odoo-web/pull/35.

In this PR, I have updated code to delete users section from  "Update my Dashboard configuration" and added boxes based on user groups.

![update_boxes](https://user-images.githubusercontent.com/36560391/104715157-28e29100-574c-11eb-96b7-411ba72c001d.png)

I have to add new menu for all user's dashboard boxes as you can import those and update through xls or csv file.
Here is videos to show how to update welcome string, welcome description and boxes data.
1. https://www.loom.com/share/ecadb4ad86574f348e5d41bbfab0bbc2
2. https://www.loom.com/share/ad9504423aac4a73af4918a8077ad4d6
3. https://www.loom.com/share/09bab116a54946f7a87b8b0f6a8f7c13
4. https://www.loom.com/share/2db440a5686a4b1294a0e2738d645520

If you want to add then there is already "Update my Dashboard configuration"  to add based on groups.

I have tried to add and update all data from one menu but it doesn't works that's why added new menu for boxes and updated data separately.

Here is videos that shows errors and tried steps to add and update in one shot.
1. https://www.loom.com/share/86eb0aaaa7d246c59633e36188d906c4
2. https://www.loom.com/share/8c57931508c94e929c5630cb9c2a7681
3. https://www.loom.com/share/8ff10132feb64a748b3e34c3d9d73be1
4. https://www.loom.com/share/f98f603bf9434d9690803869dc2c523e
5. https://www.loom.com/share/1b63fc5d0083428aad2cc2ea46e6a6ea
6. https://www.loom.com/share/9d510f88e91544459c0c1b54c3d2c7d0
7. https://www.loom.com/share/a6af951cba18428b936b2d20e02d2581

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by Radhika435** [comment] 2021-01-18 08:13
Hi @rupareliyahemangi145 
Can we take a meeting today to discuss about the functionality of the dashboard.
Please join the below link at 14:30 IST 

https://meet.jit.si/af_project_fenix

Thanks,
Radhika

**Comment by rupareliyahemangi145** [comment] 2021-01-18 08:26
Yes sure, @Radhika435

**Comment by Radhika435** [comment] 2021-01-18 09:32
Hi @rupareliyahemangi145 
For now please remove user option from Dashboard boxes
BR,
Radhika

**Comment by rupareliyahemangi145** [comment] 2021-01-18 09:37
Ok @Radhika435

**Comment by rupareliyahemangi145** [comment] 2021-01-18 10:47
Hello @Radhika435 

I have created PR https://github.com/vertelab/odoo-web/pull/36 to prevent user selection from Dashboard boxes.
Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by Radhika435** [comment] 2021-01-19 11:19
Hi @rupareliyahemangi145 

1)The import functionality is not working as intended and showing a warning message that it cant be configured manually. Similar error when importing as well.
![image](https://user-images.githubusercontent.com/59916603/105025561-c809d000-5a4d-11eb-9fbb-21784666f30c.png)
2)I wanted to select the groups to configure the Dashboard and boxes but not through the users.
3)Now  at least I am not able to configure the boxes manually by selecting the groups.(was there before)

Please check and give me your input soon.

FYI, @FredrikArvas 

BR,
Radhika

**Comment by rupareliyahemangi145** [comment] 2021-01-19 12:02
Hello @Radhika435 

1)The import functionality is not working as intended and showing a warning message that it cant be configured manually. Similar error when importing as well.
- Export and import functionality is to update box details via xls or csv file. If you want to create boxes based on group then there is menu 'Add Items to multiple users'.

2)I wanted to select the groups to configure the Dashboard and boxes but not through the users.
- This is already done with 'Add Items to multiple users'.

 3)Now at least I am not able to configure the boxes manually by selecting the groups.(was there before)
- Don't understand this point.

**Comment by Radhika435** [comment] 2021-01-19 12:27
hi @rupareliyahemangi145 
can we take the short call now

Link: https://meet.jit.si/af_project_fenix

BR,
Radhika

**Comment by rupareliyahemangi145** [comment] 2021-01-19 13:15
Hello @Radhika435 

Sorry I missed your comment. Please schedule call tomorrow.

**Comment by Radhika435** [comment] 2021-01-19 14:21
Hi @rupareliyahemangi145 

We can take a call tomorrow at 12:30 IST
Link: https://meet.jit.si/af_project_fenix

BR,
Radhika

**Comment by rupareliyahemangi145** [comment] 2021-01-20 04:46
Ok @Radhika435

**Comment by rupareliyahemangi145** [comment] 2021-01-20 08:08
Hello @Radhika435  

Here is points we discussed in meeting.
1. Remove gray color from box. Add same color which is in background. 
2. Remove border when user click on dashboard.
3. Need to update welcome data based on group separately.
4. Without title, subtitle, description don't allow gray box
5. Need to list groups and remove/add boxes based on group. So when new user create he/she can see boxes based on assigned groups.Also already created user will assign with new group or remove group from exiting user, user can see boxes based on group.
6. Server action for report right user assigned with right group or not. For this want xls report? That shows user's list, groups list and boxes list?

Please let me know If I am missing anything. 

@FredrikArvas  and @Radhika435 Please discuss and should I need to give estimation for above points?

**Comment by Radhika435** [comment] 2021-01-20 08:09
Hi @rupareliyahemangi145 
Could you please post the points that we discussed in our meeting

Thanks,
Radhika

**Comment by Radhika435** [comment] 2021-01-25 09:41
Hej @rupareliyahemangi145 ¨
Hope you are doing great!
For the above points,
1 = ok
2 = ok
3 = ok
4 = ok
5 = ok
6 = excel-export is fine. I do not think this should be necessary, since the module should work with groups, not users. (not necessary)
Please do all the changes from 1 to 5 and 6 is not necessary

Got ok from client so you can start working on this.

FIY @FredrikArvas 

Thanks & Best regards,
Radhika

**Comment by rupareliyahemangi145** [comment] 2021-01-25 12:08
Ok @Radhika435 I will start work on 1 to 5.

**Comment by rupareliyahemangi145** [comment] 2021-01-26 14:29
Hello @Radhika435 and @FredrikArvas 

I have create PR https://github.com/vertelab/odoo-web/pull/37 for following 5 points.

1. Remove gray color from box. Add same color which is in background.
2. Remove border when user click on dashboard.
3. Need to update welcome data based on group separately.
4. Without title, subtitle, description don't allow gray box
5. Need to list groups and remove/add boxes based on group. So when new user create he/she can see boxes based on assigned groups.Also already created user will assign with new group or remove group from exiting user, user can see boxes based on group.

Here is video to show how you can add boxes based on group and when you remove access, box will remove automatically.
https://www.loom.com/share/fed151cd588d41b3ba66581447853ad6

There was some issue on my loom account after prepared one video so can't prepare more videos to show that when new user will be added in system, boxes will add automatically based on assigned groups.
Also added new menu 'Update welcome data' to update welcome data based on groups.

Please test it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by Radhika435** [comment] 2021-01-28 16:47
Hi @rupareliyahemangi145 

1)Changes seems to be good but geeting some error messages when editing boxes especially pictures.
2)Cant edit the welcome text once created for groups need to create again.
3)Welcome text must be seen on all the groups along boxes but now its showing only for one group(latest given access to).
 
we will take a meeting before executing the above changes.

Are you available to join the meeting tomorrow at 1:00 IST?
Link: https://meet.jit.si/af_project_fenix

Best regards,
Radhika Thadivaka

**Comment by rupareliyahemangi145** [comment] 2021-01-29 04:35
Hello @Radhika435 

Yes I will available at 1:00 IST.

**Comment by rupareliyahemangi145** [comment] 2021-01-29 08:18
@FredrikArvas  and @Radhika435 

Here is points which we have discussed in meeting:
1. Groups in 'All users Dashboard Configuration' list.
2. Group dashboard boxes access error when changing language of user.
3. Need to add Welcome description field in Groups after Group name. So can add welcome description based on group instead of overwrite whole description.
For e.g., You have default description **'You will soon be able to visualise and perform all your daily tasks as a FA here. You can already create accounts and handle different permission rules to your employees under the tab Administration in the menu bar.**'.
Now you are adding welcome description in sale manager group that **'You will soon be able to list your sale orders.**' and giving access of sale manager to user.
Then Welcome description wiil be:
**You will soon be able to visualise and perform all your daily tasks as a FA here. You can already create accounts and handle different permission rules to your employees under the tab Administration in the menu bar.
You will soon be able to list your sale orders.**
4. JS error sometime when changing description or editing image.

Please check it and let me know when I can start work with this points.

Thanks.

Regards,
Hemangi.

**Comment by Radhika435** [comment] 2021-02-01 08:29
Hi @rupareliyahemangi145 
you can start with the changes.

BR,
Radhika

**Comment by rupareliyahemangi145** [comment] 2021-02-01 08:54
Ok @Radhika435

**Comment by rupareliyahemangi145** [comment] 2021-02-02 05:43
Hello @Radhika435  and @FredrikArvas 

Create PR https://github.com/vertelab/odoo-web/pull/38 to solve following points.

1. Groups in 'All users Dashboard Configuration' list.
2. Group dashboard boxes access error when changing language of user.
3. Need to add Welcome description field in Groups after Group name. So can add welcome description based on group instead of overwrite whole description.

Could not reproduce 4th JS error.

Here is videos for three points.
https://www.loom.com/share/7fd422d82cbb47d7aa823642723f3cdc
https://www.loom.com/share/be934ee36a8a4e85a7d2d64a4a598673
https://www.loom.com/share/55ecd731bba84209b45c4aa69270d451

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by arturchilangwa-vertel** [comment] 2021-02-02 07:47
@Radhika435 @FredrikArvas 
I have not tested the functionality of https://github.com/vertelab/odoo-web/pull/38, but the code looked good and the module was successfully installed on my machine.

**Comment by Radhika435** [comment] 2021-02-02 10:56
@arturchilangwa-vertel 
Ok thank you Artur
I will take a look on the functionality

**Comment by Radhika435** [comment] 2021-02-05 15:03
Hi @rupareliyahemangi145 
Now a user who have access to "Admin Settings" and "My dashboard manger" are able to configure the dashboard.
Change it so that the user with "My dashboard manager" role can configure the dashboard.(all users who have My dashboard manger level"can configure the dashboard )

Also hide the following on the  Dashboard menu.
"All users Dashboard configuration"
"Add items to multiple users"
"Images"
"Dashboard configuration boxes"

Best regards,
Radhika.

**Comment by rupareliyahemangi145** [comment] 2021-02-06 05:51
Hello @Radhika435 
Need to hide following dashboard menus for all users? Even Admin Settings?
"All users Dashboard configuration"
"Add items to multiple users"
"Images"
"Dashboard configuration boxes"

I have question for We need to show 'My Dashboard Configuration' menu to users who has 'My Dashboard Manager' access. So user can see/edit only his dashboard configuration, right?

And Groups menu need to show if user has "Admin Settings" and "My Dashboard Manager" group, right?

Thanks.

Regards,
Hemangi.

**Comment by Radhika435** [comment] 2021-02-09 09:14
Hi @rupareliyahemangi145 
we will take a call today, let me know your availability
Best regards,
Radhika

**Comment by rupareliyahemangi145** [comment] 2021-02-09 10:32
Hello @Radhika435 

We can call at 5:00 PM IST. after 1 hour.

**Comment by Radhika435** [comment] 2021-02-09 12:20
Hi @rupareliyahemangi145 
Sorry just saw your message 
can we take now?
Link : https://meet.jit.si/af_project_fenix

BR,
Radhika

**Comment by rupareliyahemangi145** [comment] 2021-02-09 13:55
Hi @Radhika435 

Sorry I missed your message. Schedule meeting tomorrow. Except between 11 AM to 1 PM IST. Otherwise I will be available at 10 to 11 AM IST, 1 PM to 7 PM IST.

**Comment by Radhika435** [comment] 2021-02-09 14:24
Hi @rupareliyahemangi145 

we can take at 1 pm IST tomorrow
Link : https://meet.jit.si/af_project_fenix

BR,
Radhika

**Comment by rupareliyahemangi145** [comment] 2021-02-10 04:43
Ok @Radhika435

**Comment by rupareliyahemangi145** [comment] 2021-02-10 07:52
Hello @Radhika435 

Here things which we have discussed on meeting:
If user has not Dashboard manager group then need to show only start page.There will be no menu.
If use has Dashboard manager then need to show **Groups**, **My Dashboard Configuration**, **All users Dashboard configuration** and **Update welcome data**.Need to hide **Add item to multiple user**, **Images** and **Dashboard boxes configuration**.

Thanks

Regards,
Hemangi.

**Comment by Radhika435** [comment] 2021-02-10 07:59
Yes @rupareliyahemangi145 
Please proceed .

**Comment by rupareliyahemangi145** [comment] 2021-02-10 08:11
Ok @Radhika435

**Comment by rupareliyahemangi145** [comment] 2021-02-11 10:28
Hello @Radhika435 

I have created PR https://github.com/vertelab/odoo-web/pull/42 for menu changes.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi.

**Comment by rupareliyahemangi145** [comment] 2021-02-11 10:33
@Radhika435 Here is video to show changes:
https://www.loom.com/share/91d64013c2e04dafae8f21913ca4c162

Thanks.

Regards,
Hemangi

**Comment by nils-vertel** [comment] 2021-02-16 12:01
Merged: https://github.com/vertelab/odoo-web/pull/42

**Comment by Radhika435** [comment] 2021-02-25 12:05
Hi @rupareliyahemangi145 
Do you have time for a call now or later today?
Please reply soon and use the below link for a meeting.

Link : https://meet.jit.si/af_project_fenix

Thanks & best regards,
Radhika thadivaka

**Comment by rupareliyahemangi145** [comment] 2021-02-25 12:15
Hi @Radhika435 

Yes Let's connect.

**Comment by Radhika435** [comment] 2021-02-25 12:17
@rupareliyahemangi145 
please join the link

**Comment by Radhika435** [comment] 2021-02-25 12:25
Hi @rupareliyahemangi145 
Could you share your number here?

**Comment by rupareliyahemangi145** [comment] 2021-02-25 12:43
Hello @Radhika435 

I understood that If you have added boxes in 3 groups with same description and use is assigned with these 3 groups then use can see duplicate boxes on Dashboard.

Let me investigate about it. I will get back to you soon with suggestion.

Thanks.

Regards,
Hemangi.

**Comment by rupareliyahemangi145** [comment] 2021-02-25 13:07
Hello @Radhika435 

Can we connect again? I found one solution and want show you.

**Comment by rupareliyahemangi145** [comment] 2021-02-25 14:05
Hello @Radhika435 
I will discuss with Anil tomorrow and get back to you soon.

Regards,
Hemangi.

**Comment by rupareliyahemangi145** [comment] 2021-02-26 09:52
Hello @Radhika435 

I have created PR https://github.com/vertelab/odoo-web/pull/47 to solve duplicate issue.

Here is some videos to show it:
https://www.loom.com/share/4c53b1234deb4743bf2a457db99a3409
https://www.loom.com/share/f06dde556584450293b85bf2f862686b
https://www.loom.com/share/206b893fbaa64f8aa033f7e7383268c2

Please test it from your side and let me know if anything.

Thanks

Regards,
Hemangi.

**Comment by Radhika435** [comment] 2021-02-26 13:19
Hi @rupareliyahemangi145 
Your first video is paused in the middle so unable to see the total functionality.
could you resend the video once again.

Best regards,
Radhika

**Comment by rupareliyahemangi145** [comment] 2021-02-26 14:30
Hello @Radhika435 

I will send you new video tomorrow.

**Comment by rupareliyahemangi145** [comment] 2021-02-27 05:18
Hello @Radhika435 

Here is new video:
https://www.loom.com/share/3697fab243ca47c6941ac557e419df07

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi

**Comment by Radhika435** [comment] 2021-03-01 09:37
Hello @rupareliyahemangi145 

Could you please this bug as wll with welcome text that i mentioned in the call.
![image](https://user-images.githubusercontent.com/59916603/109478912-1b723380-7a7a-11eb-873a-fc2e8cc4b104.png)

BR,
Radhika

**Comment by rupareliyahemangi145** [comment] 2021-03-01 12:19
Hello @Radhika435 

I have create PR https://github.com/vertelab/odoo-web/pull/48 to prevent duplicate and for translation.

I have added translation inside po file for mentioned screenshot. So upgrade module with latest code and load translation from Setting >> Translation >> Load a Translation.

And for **Welcome** I didn't found way to translate it from po file because It is a default data of field. So I have updated code to use "Bienvenida" default instead of **Welcome**.

Here is videos for testing:
https://www.loom.com/share/3622b3fbfcf3499db634a50e31fc742e
https://www.loom.com/share/afd7f1b02158464dbb080a6f1d5a4b0c

Please test it and let me know if anything.

Thanks

Regards,
Hemangi.

**Comment by rupareliyahemangi145** [comment] 2021-03-02 11:11
Hello @Radhika435 

I have pushed code for server action to update welcome message. Created new commit in same PR https://github.com/vertelab/odoo-web/pull/48.

Server action name is **Update Welcome String**.

Please check it and let me know if anything.

Thanks.

Regards,
Hemangi

**Comment by rupareliyahemangi145** [comment] 2021-03-02 12:04
Hello @Radhika435 

Here is video for above commit. 
https://www.loom.com/share/62772fc7323446178deab41bbc77218a

Thanks.

Regards,
Hemangi.

**Closed as completed** 2021-04-24 15:38 UTC
Labels: enhancement
