### ISSUE TITLE
AFC-613 Main menu's text doesn't render properly on screen readers (a11y)

### ISSUE THREAD

**Issue by Viltersten** [vertelab/odoo-af#276] opened 2020-10-21 09:59 UTC
**Userstory:** 
As a user, I want to see accessibility (a11y)-enabled text "Main Menu" instead or beside the "waffle"-icon on the "main menu"-bar.

**Module name:**
odoo-af/af_backend_tema

**Test-steps:**
Using a screen reader, check the presented text to read "mny+ Huvudmeny" and "mny- Huvudmeny" dependent on the fold state of the main menu.

**Branch name:** 
12.0-AFC-613_update_to_main_menu

**Estimate:** 
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by Viltersten** [comment] 2020-10-21 10:05
This issue relates to [this one](https://github.com/vertelab/odoo-af/issues/263) as a part of a11y customization.

**Comment by rupareliyahemangi145** [comment] 2020-10-22 06:01
Hello @FredrikArvas 

I checked  odoo-af/af-a11y module but it added only one asset.xml file. Don't understand what it do.
Also checked AF-660 but as screenshot of output I think it allows to list Contacts in website.

So I am bit confused what I need to do here.

**Comment by FredrikArvas** [comment] 2020-10-22 06:45
Hi Hemangi, 
It is my fault. We have several new developers to the team and we all learn. It is my responsibility to check the Issues before we submit them. 

In this case Konrad suggested a new module, where he have done all the right steps to submit it, but we would like an enhancement to an existing module. 
Thanks

**Comment by rupareliyahemangi145** [comment] 2020-10-22 11:16
Hello @FredrikArvas 

Can you please give me information about module which Konrad done?

**Comment by FredrikArvas** [comment] 2020-10-22 18:41
Please go for the normal af_backend_theme-module.
Thanks

**Comment by rupareliyahemangi145** [comment] 2020-10-23 05:01
Hello @FredrikArvas 

Sorry I don't understand what I need to in waffle icon. I don't know about a11y-enabled text "Huvudmeny".

**Comment by FredrikArvas** [comment] 2020-10-23 08:55
HI
I have updated the description: 
Please add the text "Main Menu" instead of or beside the waffle-icon, and send a screen-shot.

**Comment by rupareliyahemangi145** [comment] 2020-10-23 09:11
Ok Sure @FredrikArvas

**Comment by rupareliyahemangi145** [comment] 2020-10-23 09:38
Hello @FredrikArvas 

Here are screenshots:

1. Removed Waffle and added 'Main Menu'

![added_text_without_waffel](https://user-images.githubusercontent.com/36560391/96988042-71215700-1541-11eb-83f3-cda02beff75a.png)

2. Added 'Main Menu' test with waffle.

![added_texr](https://user-images.githubusercontent.com/36560391/96988094-80080980-1541-11eb-9ce6-b3e42d0f7863.png)

Please check it let me know which one you prefer.

Thanks.

**Comment by rupareliyahemangi145** [comment] 2020-10-24 05:50
Spent time 1 hour and 30 mins(With analysis, discussion and development)

**Comment by Viltersten** [comment] 2020-10-26 04:13
Which branch has this been committed in?

**Comment by rupareliyahemangi145** [comment] 2020-10-26 04:43
Hello @Viltersten 

Didn't committed this issue, I have just added screenshots to show look with both **waffle with text** and **only text**.

Please let me know which one preferable only 'Main Menu' or waffle with 'Main Menu', then I will commit for that?

**Comment by Viltersten** [comment] 2020-10-26 04:51
The final decision will depend on how it renders in a screen reader.

If the waffle is just a Unicode character in front of the "main menu" text (which in Swedish reads "Huvudmeny", which at the moment is unimportant), I'd suggest without it. If it's an image (which I understand is the case at AF's installation), I'd go with the waffle.

So I guess it's your call. My consideration is WCAG and A11Y, so the visual sense isn't relevant. Take whichever is ready to commit right now and submit it, please. I'll check it out right away, as long as I know the name of the branch.

**Comment by Viltersten** [comment] 2020-10-26 05:05
@rupareliyahemangi145 When do you estimate that it will be committed for review, please?

**Comment by rupareliyahemangi145** [comment] 2020-10-26 10:36
Hello @Viltersten 

Let me commit it.

**Comment by rupareliyahemangi145** [comment] 2020-10-26 11:04
Hello @Viltersten 

Created PR https://github.com/vertelab/odoo-af/pull/294 for only text instead of waffle.

Created PR https://github.com/vertelab/odoo-af/pull/295 for text with waffle.

Please test it and let me know if anything.

**Comment by rupareliyahemangi145** [comment] 2020-10-26 11:07
Spent 30 mins(0.5) for Creating two PR.

**Comment by Viltersten** [comment] 2020-11-03 23:20
I've tested a set of different angles and we've discovered som unexpected behaviors. After a discussion with out a11y tester, we inferred a certain HTML markup that satisfies the impaired's needs (as far we can tell at the moment). In order to lower the complexity, I've created a new branch incorporating your commits, amending the results of a11y testing.

**Comment by HarhuTech** [comment] 2020-11-09 09:14
@Viltersten : Does your last comment related to improvements on the last submission done by @rupareliyahemangi145 ?

If you are requesting the improvements or suggestion to improve anything. can you please provide any example of expected result? because we didn't understand exactly what changes we need to do based on your last comment.

Regards,
Anil

**Comment by Viltersten** [comment] 2020-11-09 16:53
That's correctly understood. The two suggestions provided are only visual, whereas the actual functionality of the button wasn't implemented. Please note that I'm (almost always) referring to the functionality as required by the impaired users. Let me offer an example to provide you with the sense of trickiness when developing a11y enabled solutions.

For instance, the menu unfolding for your eyes on the screen is not unfolding for a blind reader. That specific functionality is mimicked by a plus/minus sign in front of the title of the menu. That way, a visually impaired user can be made aware that there's (possibly lengthy) context under the element, should they choose to unfold and investigate it. Otherwise, they may choose to skip to the next item on the page.

The screen readers are rendering Braille Script and work extensively with ARIA attributes. It's the state of those that control what's regarded as equivalent to visible element, alarming popups, notification badges etc. It this particular example, the folding state is described by the attribute `aria-expanded`, as my sample code shows. It needs to be altered in order to maintain WCAG defined conditions, which are a legal requirement in out kingdom since mid September.

The other comment I made was about my discovery that Odoo seemingly doesn't treat other attributes or even standard HTML markup in an expected way. It got me curious as to why. And, of course worried, that it may lead to complications while implementing the a11y related adaptations.

As I sense this might be a complicated subject and an unfamiliar territory to staff not used to HTML and web development, I suggest a live meeting so we can discuss it. Fredrik suggested Meet, which I'm happy with. However, please don't feel limited by that and pick any communication strategy that we both can efficiently work with.

Your team, being placed in a different time zone, are more than welcome to use that geographical predisposition to our advantage. I'm flexible with working hours, so if it's too difficult to find a time slot during conventional working hours in Sweden, we can go late in the evening as well. Below is my current availability. Please note that it's subject to change on short notice. I recommend confirmation by email, konrad.viltersten@arbetsformedlingen.se.

Tue: 0815-0900, 1130-1215, 1615-any
Wed: 1615-any
Thu: 1030-1330

**Comment by AnilKesariya** [comment] 2020-11-10 09:05
Hi @Viltersten : 

I confirmed to let's connect today to clarify the doubts on this would be more easier.

I will also confirm you via email for the time slot you've added are the sweden time right?
Regards,

**Comment by AnilKesariya** [comment] 2020-11-10 13:06
@FredrikArvas : Can you allocate another person for this issue, we are not getting what changes or what improvements we need to complete this issue.

**Comment by FredrikArvas** [comment] 2020-11-10 20:17
Hi Anil, 
yes, no problem. You are both doing a great job. We have more work waiting, I am just stuck with meetings and instructing my collegues to create git-issues. 
Thanks
Fredrik

**Comment by FredrikArvas** [comment] 2020-11-11 21:00
@Viltersten - I have looked at your suggestions and we need to talk about them before we make a new issue. 
https://github.com/vertelab/odoo-af/blob/AFC-613/af_backend_tema/static/src/xml/menu.xml
Let's talk tomorrow!
/Fredrik

**Closed by FredrikArvas** 2020-11-11 21:00 UTC
Labels: a11y, enhancement
